site_name: My Docs
site_url: https://moutyque.github.io/poulapin.github.io/
site_author: you
site_description: a short description of your website

nav:
  - Mission: index.md
  - first:

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml